In [6]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

In [2]:
# Downloading imdb top 250 movie's data
url = 'http://www.imdb.com/chart/top'
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

In [6]:
#print(soup.prettify())
#list(soup.children)
[type(item) for item in list(soup.children)]

[bs4.element.NavigableString,
 bs4.element.Doctype,
 bs4.element.NavigableString,
 bs4.element.Tag,
 bs4.element.NavigableString]

In [15]:
#html = list(soup.children)[3]
#list(html.children)
#body = list(html.children)[3]
#list(body.children)[3]

[<p>The Top Rated Movie list only includes feature films.</p>,
 <p class="imdb-footer__copyright footer__copyright">© 1990-<!-- -->2022<!-- --> by IMDb.com, Inc.</p>]

In [17]:
#soup.find_all('p')
soup.select("div p")

[<p>The Top Rated Movie list only includes feature films.</p>,
 <p class="imdb-footer__copyright footer__copyright">© 1990-<!-- -->2022<!-- --> by IMDb.com, Inc.</p>]

In [18]:
movies = soup.select('td.titleColumn')
crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
ratings = [b.attrs.get('data-value') for b in soup.select('td.posterColumn span[name=ir]')]

In [22]:
# create a empty list for storing
# movie information
list = []

# Iterating over movies to extract
# each movie's details
for index in range(0, len(movies)):
	
	# Separating movie into: 'place',
	# 'title', 'year'
	movie_string = movies[index].get_text()
	movie = (' '.join(movie_string.split()).replace('.', ''))
	movie_title = movie[len(str(index))+1:-7]
	year = re.search('\((.*?)\)', movie_string).group(1)
	place = movie[:len(str(index))-(len(movie))]
	data = {"place": place,
			"movie_title": movie_title,
			"rating": ratings[index],
			"year": year,
			"star_cast": crew[index],
			}
	list.append(data)

In [23]:
for movie in list:
	print(movie['place'], '-', movie['movie_title'], '('+movie['year'] +
		') -', 'Starring:', movie['star_cast'], movie['rating'])

1 - The Shawshank Redemption (1994) - Starring: Frank Darabont (dir.), Tim Robbins, Morgan Freeman 9.235228911762258
2 - The Godfather (1972) - Starring: Francis Ford Coppola (dir.), Marlon Brando, Al Pacino 9.156085111265273
3 - The Dark Knight (2008) - Starring: Christopher Nolan (dir.), Christian Bale, Heath Ledger 8.989211634325583
4 - The Godfather Part II (1974) - Starring: Francis Ford Coppola (dir.), Al Pacino, Robert De Niro 8.984088961727375
5 - 12 Angry Men (1957) - Starring: Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb 8.95075650853193
6 - Schindler's List (1993) - Starring: Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes 8.937953929199402
7 - The Lord of the Rings: The Return of the King (2003) - Starring: Peter Jackson (dir.), Elijah Wood, Viggo Mortensen 8.928577087867515
8 - Pulp Fiction (1994) - Starring: Quentin Tarantino (dir.), John Travolta, Uma Thurman 8.848453178833672
9 - The Lord of the Rings: The Fellowship of the Ring (2001) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen 8.808643684100197
1 -  Il buono, il brutto, il cattivo (1966) - Starring: Sergio Leone (dir.), Clint Eastwood, Eli Wallach 8.79106395468745
11 - Forrest Gump (1994) - Starring: Robert Zemeckis (dir.), Tom Hanks, Robin Wright 8.767645153282269
12 - Fight Club (1999) - Starring: David Fincher (dir.), Brad Pitt, Edward Norton 8.748761515402494
13 - The Lord of the Rings: The Two Towers (2002) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen 8.733815958133682
14 - Inception (2010) - Starring: Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt 8.733220189552023
15 - The Empire Strikes Back (1980) - Starring: Irvin Kershner (dir.), Mark Hamill, Harrison Ford 8.700093023107145
16 - The Matrix (1999) - Starring: Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne 8.66990640087145
17 - Goodfellas (1990) - Starring: Martin Scorsese (dir.), Robert De Niro, Ray Liotta 8.652358196399701
18 - One Flew Over the Cuckoo's Nest (1975) - Starring: Milos Forman (dir.), Jack Nicholson, Louise Fletcher 8.639536911706845
19 - Se7en (1995) - Starring: David Fincher (dir.), Morgan Freeman, Brad Pitt 8.604305862811383
20 - Shichinin no samurai (1954) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura 8.599296276627511
21 - It's a Wonderful Life (1946) - Starring: Frank Capra (dir.), James Stewart, Donna Reed 8.5958385546561
22 - The Silence of the Lambs (1991) - Starring: Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins 8.58822757254542
23 - Cidade de Deus (2002) - Starring: Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino 8.579666410513587
24 - Saving Private Ryan (1998) - Starring: Steven Spielberg (dir.), Tom Hanks, Matt Damon 8.578961943726355
25 - La vita è bella (1997) - Starring: Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi 8.568057907582567
26 - Interstellar (2014) - Starring: Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway 8.563838158424385
27 - The Green Mile (1999) - Starring: Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan 8.56210635318859
28 - Star Wars (1977) - Starring: George Lucas (dir.), Mark Hamill, Harrison Ford 8.550662825907139
29 - Terminator 2: Judgment Day (1991) - Starring: James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton 8.536215825395487
30 - Back to the Future (1985) - Starring: Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd 8.517922611572752
31 - Sen to Chihiro no kamikakushi (2001) - Starring: Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette 8.516247222331902
32 - Psycho (1960) - Starring: Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh 8.507513907833332
33 - The Pianist (2002) - Starring: Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann 8.506367505565605
34 - Gisaengchung (2019) - Starring: Bong Joon Ho (dir.), Song Kang-ho, Lee Sun-kyun 8.497875930936921
35 - Léon (1994) - Starring: Luc Besson (dir.), Jean Reno, Gary Oldman 8.496521409204059
36 - The Lion King (1994) - Starring: Roger Allers (dir.), Matthew Broderick, Jeremy Irons 8.488404065996583
37 - Gladiator (2000) - Starring: Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix 8.486355072741986
38 - American History X (1998) - Starring: Tony Kaye (dir.), Edward Norton, Edward Furlong 8.482940863498069
39 - The Departed (2006) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon 8.475652682286887
40 - The Usual Suspects (1995) - Starring: Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne 8.472461134350368
41 - The Prestige (2006) - Starring: Christopher Nolan (dir.), Christian Bale, Hugh Jackman 8.468803076407793
42 - Whiplash (2014) - Starring: Damien Chazelle (dir.), Miles Teller, J.K. Simmons 8.464759546863316
43 - Casablanca (1942) - Starring: Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman 8.463296031582521
44 - Seppuku (1962) - Starring: Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama 8.45492660760083
45 - The Intouchables (2011) - Starring: Olivier Nakache (dir.), François Cluzet, Omar Sy 8.454318628915152
46 - Hotaru no haka (1988) - Starring: Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi 8.453649656593942
47 - Modern Times (1936) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard 8.448727868254808
48 - Once Upon a Time in the West (1968) - Starring: Sergio Leone (dir.), Henry Fonda, Charles Bronson 8.444713087935858
49 - Rear Window (1954) - Starring: Alfred Hitchcock (dir.), James Stewart, Grace Kelly 8.436082844728064
50 - Alien (1979) - Starring: Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt 8.434081631540229
51 - City Lights (1931) - Starring: Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill 8.433703736565189
52 - Nuovo Cinema Paradiso (1988) - Starring: Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale 8.43359707610915
53 - Apocalypse Now (1979) - Starring: Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando 8.424126431713445
54 - Memento (2000) - Starring: Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss 8.422584666495489
55 - Raiders of the Lost Ark (1981) - Starring: Steven Spielberg (dir.), Harrison Ford, Karen Allen 8.40872074829019
56 - Django Unchained (2012) - Starring: Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz 8.406437905575888
57 - WALL·E (2008) - Starring: Andrew Stanton (dir.), Ben Burtt, Elissa Knight 8.394252753587958
58 - The Lives of Others (2006) - Starring: Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck 8.385247527026161
59 - Sunset Blvd (1950) - Starring: Billy Wilder (dir.), William Holden, Gloria Swanson 8.380056993778629
60 - Paths of Glory (1957) - Starring: Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker 8.371890885165287
61 - The Shining (1980) - Starring: Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall 8.365816639040062
62 - The Great Dictator (1940) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard 8.365771031017276
63 - Avengers: Infinity War (2018) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth 8.360612542570601
64 - Witness for the Prosecution (1957) - Starring: Billy Wilder (dir.), Tyrone Power, Marlene Dietrich 8.359769391700468
65 - Aliens (1986) - Starring: James Cameron (dir.), Sigourney Weaver, Michael Biehn 8.343186592336902
66 - Spider-Man: Into the Spider-Verse (2018) - Starring: Bob Persichetti (dir.), Shameik Moore, Jake Johnson 8.33413996292487
67 - American Beauty (1999) - Starring: Sam Mendes (dir.), Kevin Spacey, Annette Bening 8.333678395999893
68 - Dr Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) - Starring: Stanley Kubrick (dir.), Peter Sellers, George C. Scott 8.33009044763507
69 - The Dark Knight Rises (2012) - Starring: Christopher Nolan (dir.), Christian Bale, Tom Hardy 8.327303386289502
70 - Oldeuboi (2003) - Starring: Park Chan-wook (dir.), Choi Min-sik, Yoo Ji-tae 8.320499898851706
71 - Amadeus (1984) - Starring: Milos Forman (dir.), F. Murray Abraham, Tom Hulce 8.316043015628006
72 - Joker (2019) - Starring: Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro 8.31599970661959
73 - Inglourious Basterds (2009) - Starring: Quentin Tarantino (dir.), Brad Pitt, Diane Kruger 8.31515869138722
74 - Coco (2017) - Starring: Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal 8.314617746463615
75 - Toy Story (1995) - Starring: John Lasseter (dir.), Tom Hanks, Tim Allen 8.314253552105994
76 - Braveheart (1995) - Starring: Mel Gibson (dir.), Mel Gibson, Sophie Marceau 8.313863493707228
77 - Das Boot (1981) - Starring: Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer 8.312291551352944
78 - Avengers: Endgame (2019) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Evans 8.304278031681356
79 - Mononoke-hime (1997) - Starring: Hayao Miyazaki (dir.), Yôji Matsuda, Yuriko Ishida 8.303375805227772
80 - Once Upon a Time in America (1984) - Starring: Sergio Leone (dir.), Robert De Niro, James Woods 8.296617538573301
81 - Good Will Hunting (1997) - Starring: Gus Van Sant (dir.), Robin Williams, Matt Damon 8.289238436684894
82 - Top Gun: Maverick (2022) - Starring: Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly 8.288594413451452
83 - Kimi no Na wa (2016) - Starring: Makoto Shinkai (dir.), Ryûnosuke Kamiki, Mone Kamishiraishi 8.27997500982327
84 - Requiem for a Dream (2000) - Starring: Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto 8.275554330587816
85 - Singin' in the Rain (1952) - Starring: Stanley Donen (dir.), Gene Kelly, Donald O'Connor 8.273669497004537
86 - Toy Story 3 (2010) - Starring: Lee Unkrich (dir.), Tom Hanks, Tim Allen 8.273537569223675
87 - 3 Idiots (2009) - Starring: Rajkumar Hirani (dir.), Aamir Khan, Madhavan 8.273452964271353
88 - Tengoku to jigoku (1963) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Yutaka Sada 8.270368511695434
89 - Star Wars: Episode VI - Return of the Jedi (1983) - Starring: Richard Marquand (dir.), Mark Hamill, Harrison Ford 8.265636080663437
90 - Capharnaüm (2018) - Starring: Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw 8.263082875079876
91 - Eternal Sunshine of the Spotless Mind (2004) - Starring: Michel Gondry (dir.), Jim Carrey, Kate Winslet 8.262805638101442
92 - 2001: A Space Odyssey (1968) - Starring: Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood 8.262765500417942
93 - Reservoir Dogs (1992) - Starring: Quentin Tarantino (dir.), Harvey Keitel, Tim Roth 8.261623181196589
94 - Jagten (2012) - Starring: Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen 8.256034390438135
95 - Idi i smotri (1985) - Starring: Elem Klimov (dir.), Aleksey Kravchenko, Olga Mironova 8.253470599788606
96 - Citizen Kane (1941) - Starring: Orson Welles (dir.), Orson Welles, Joseph Cotten 8.253261320382027
97 - M - Eine Stadt sucht einen Mörder (1931) - Starring: Fritz Lang (dir.), Peter Lorre, Ellen Widmann 8.252251400647705
98 - Lawrence of Arabia (1962) - Starring: David Lean (dir.), Peter O'Toole, Alec Guinness 8.252035931566736
99 - North by Northwest (1959) - Starring: Alfred Hitchcock (dir.), Cary Grant, Eva Marie Saint 8.248070962435722
10 -  Vertigo (1958) - Starring: Alfred Hitchcock (dir.), James Stewart, Kim Novak 8.24456101187658
101 - Le fabuleux destin d'Amélie Poulain (2001) - Starring: Jean-Pierre Jeunet (dir.), Audrey Tautou, Mathieu Kassovitz 8.243886567995707
102 - A Clockwork Orange (1971) - Starring: Stanley Kubrick (dir.), Malcolm McDowell, Patrick Magee 8.241482630558336
103 - The Apartment (1960) - Starring: Billy Wilder (dir.), Jack Lemmon, Shirley MacLaine 8.239717546652344
104 - Ikiru (1952) - Starring: Akira Kurosawa (dir.), Takashi Shimura, Nobuo Kaneko 8.238810653397648
105 - Double Indemnity (1944) - Starring: Billy Wilder (dir.), Fred MacMurray, Barbara Stanwyck 8.238465596315216
106 - Full Metal Jacket (1987) - Starring: Stanley Kubrick (dir.), Matthew Modine, R. Lee Ermey 8.238126543679474
107 - Scarface (1983) - Starring: Brian De Palma (dir.), Al Pacino, Michelle Pfeiffer 8.235051121688231
108 - Hamilton (2020) - Starring: Thomas Kail (dir.), Lin-Manuel Miranda, Phillipa Soo 8.23476887710289
109 - The Sting (1973) - Starring: George Roy Hill (dir.), Paul Newman, Robert Redford 8.22739686336121
110 - To Kill a Mockingbird (1962) - Starring: Robert Mulligan (dir.), Gregory Peck, John Megna 8.226880617372789
111 - Incendies (2010) - Starring: Denis Villeneuve (dir.), Lubna Azabal, Mélissa Désormeaux-Poulin 8.224742580576374
112 - Up (2009) - Starring: Pete Docter (dir.), Edward Asner, Jordan Nagai 8.224584077705414
113 - Heat (1995) - Starring: Michael Mann (dir.), Al Pacino, Robert De Niro 8.224425896048512
114 - Taxi Driver (1976) - Starring: Martin Scorsese (dir.), Robert De Niro, Jodie Foster 8.223035383860621
115 - Jodaeiye Nader az Simin (2011) - Starring: Asghar Farhadi (dir.), Payman Maadi, Leila Hatami 8.222127995103381
116 - Metropolis (1927) - Starring: Fritz Lang (dir.), Brigitte Helm, Alfred Abel 8.221404501916354
117 - LA Confidential (1997) - Starring: Curtis Hanson (dir.), Kevin Spacey, Russell Crowe 8.220894917608142
118 - Snatch (2000) - Starring: Guy Ritchie (dir.), Jason Statham, Brad Pitt 8.218339333309732
119 - Die Hard (1988) - Starring: John McTiernan (dir.), Bruce Willis, Alan Rickman 8.218044301923898
120 - Ladri di biciclette (1948) - Starring: Vittorio De Sica (dir.), Lamberto Maggiorani, Enzo Staiola 8.217261491162057
121 - Indiana Jones and the Last Crusade (1989) - Starring: Steven Spielberg (dir.), Harrison Ford, Sean Connery 8.216991380399277
122 - 1917 (2019) - Starring: Sam Mendes (dir.), Dean-Charles Chapman, George MacKay 8.211479904018242
123 - Taare Zameen Par (2007) - Starring: Aamir Khan (dir.), Darsheel Safary, Aamir Khan 8.211182104772316
124 - Der Untergang (2004) - Starring: Oliver Hirschbiegel (dir.), Bruno Ganz, Alexandra Maria Lara 8.203754173907626
125 - Per qualche dollaro in più (1965) - Starring: Sergio Leone (dir.), Clint Eastwood, Lee Van Cleef 8.201094910649072
126 - Batman Begins (2005) - Starring: Christopher Nolan (dir.), Christian Bale, Michael Caine 8.199284145875936
127 - Dangal (2016) - Starring: Nitesh Tiwari (dir.), Aamir Khan, Sakshi Tanwar 8.199079742359405
128 - The Kid (1921) - Starring: Charles Chaplin (dir.), Charles Chaplin, Edna Purviance 8.192727180512373
129 - Some Like It Hot (1959) - Starring: Billy Wilder (dir.), Marilyn Monroe, Tony Curtis 8.191265160778423
130 - The Father (2020) - Starring: Florian Zeller (dir.), Anthony Hopkins, Olivia Colman 8.180925230544549
131 - All About Eve (1950) - Starring: Joseph L. Mankiewicz (dir.), Bette Davis, Anne Baxter 8.180637759717612
132 - Green Book (2018) - Starring: Peter Farrelly (dir.), Viggo Mortensen, Mahershala Ali 8.176459718699853
133 - The Wolf of Wall Street (2013) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Jonah Hill 8.175180117985414
134 - Judgment at Nuremberg (1961) - Starring: Stanley Kramer (dir.), Spencer Tracy, Burt Lancaster 8.17013039513337
135 - Ran (1985) - Starring: Akira Kurosawa (dir.), Tatsuya Nakadai, Akira Terao 8.164544180819648
136 - Casino (1995) - Starring: Martin Scorsese (dir.), Robert De Niro, Sharon Stone 8.164002617693452
137 - Pan's Labyrinth (2006) - Starring: Guillermo del Toro (dir.), Ivana Baquero, Ariadna Gil 8.161957992064346
138 - Unforgiven (1992) - Starring: Clint Eastwood (dir.), Clint Eastwood, Gene Hackman 8.16069778151887
139 - There Will Be Blood (2007) - Starring: Paul Thomas Anderson (dir.), Daniel Day-Lewis, Paul Dano 8.157866075027076
140 - The Truman Show (1998) - Starring: Peter Weir (dir.), Jim Carrey, Ed Harris 8.156907681063748
141 - The Sixth Sense (1999) - Starring: M. Night Shyamalan (dir.), Bruce Willis, Haley Joel Osment 8.153683833637364
142 - A Beautiful Mind (2001) - Starring: Ron Howard (dir.), Russell Crowe, Ed Harris 8.151736490144794
143 - Spider-Man: No Way Home (2021) - Starring: Jon Watts (dir.), Tom Holland, Zendaya 8.150698295040586
144 - Yôjinbô (1961) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Eijirô Tôno 8.149238032846606
145 - Shutter Island (2010) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Emily Mortimer 8.149052854066818
146 - Monty Python and the Holy Grail (1975) - Starring: Terry Gilliam (dir.), Graham Chapman, John Cleese 8.148965464587398
147 - The Treasure of the Sierra Madre (1948) - Starring: John Huston (dir.), Humphrey Bogart, Walter Huston 8.147691089671635
148 - Jurassic Park (1993) - Starring: Steven Spielberg (dir.), Sam Neill, Laura Dern 8.146386503478453
149 - The Great Escape (1963) - Starring: John Sturges (dir.), Steve McQueen, James Garner 8.141342289390051
150 - Rashômon (1950) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Machiko Kyô 8.14115851676479
151 - Kill Bill: Vol 1 (2003) - Starring: Quentin Tarantino (dir.), Uma Thurman, David Carradine 8.137944024868727
152 - No Country for Old Men (2007) - Starring: Ethan Coen (dir.), Tommy Lee Jones, Javier Bardem 8.137682657344216
153 - Finding Nemo (2003) - Starring: Andrew Stanton (dir.), Albert Brooks, Ellen DeGeneres 8.131604013704006
154 - The Thing (1982) - Starring: John Carpenter (dir.), Kurt Russell, Wilford Brimley 8.130776526543915
155 - The Elephant Man (1980) - Starring: David Lynch (dir.), Anthony Hopkins, John Hurt 8.128541324445505
156 - Chinatown (1974) - Starring: Roman Polanski (dir.), Jack Nicholson, Faye Dunaway 8.127458321381344
157 - Raging Bull (1980) - Starring: Martin Scorsese (dir.), Robert De Niro, Cathy Moriarty 8.125820752485424
158 - V for Vendetta (2005) - Starring: James McTeigue (dir.), Hugo Weaving, Natalie Portman 8.124174963692425
159 - Gone with the Wind (1939) - Starring: Victor Fleming (dir.), Clark Gable, Vivien Leigh 8.123994401450217
160 - Inside Out (2015) - Starring: Pete Docter (dir.), Amy Poehler, Bill Hader 8.12217767788501
161 - Lock, Stock and Two Smoking Barrels (1998) - Starring: Guy Ritchie (dir.), Jason Flemyng, Dexter Fletcher 8.121544516218718
162 - Dial M for Murder (1954) - Starring: Alfred Hitchcock (dir.), Ray Milland, Grace Kelly 8.119487297218422
163 - El secreto de sus ojos (2009) - Starring: Juan José Campanella (dir.), Ricardo Darín, Soledad Villamil 8.117650769392613
164 - Hauru no ugoku shiro (2004) - Starring: Hayao Miyazaki (dir.), Chieko Baishô, Takuya Kimura 8.116146277641992
165 - The Bridge on the River Kwai (1957) - Starring: David Lean (dir.), William Holden, Alec Guinness 8.112369930702956
166 - Three Billboards Outside Ebbing, Missouri (2017) - Starring: Martin McDonagh (dir.), Frances McDormand, Woody Harrelson 8.111487476745133
167 - Trainspotting (1996) - Starring: Danny Boyle (dir.), Ewan McGregor, Ewen Bremner 8.111096732497453
168 - Warrior (2011) - Starring: Gavin O'Connor (dir.), Tom Hardy, Nick Nolte 8.103388644687884
169 - Fargo (1996) - Starring: Joel Coen (dir.), William H. Macy, Frances McDormand 8.102389477653064
170 - Gran Torino (2008) - Starring: Clint Eastwood (dir.), Clint Eastwood, Bee Vang 8.102371786200242
171 - Prisoners (2013) - Starring: Denis Villeneuve (dir.), Hugh Jackman, Jake Gyllenhaal 8.101036716327116
172 - Tonari no Totoro (1988) - Starring: Hayao Miyazaki (dir.), Hitoshi Takagi, Noriko Hidaka 8.093851803556651
173 - Million Dollar Baby (2004) - Starring: Clint Eastwood (dir.), Hilary Swank, Clint Eastwood 8.089224281129251
174 - Catch Me If You Can (2002) - Starring: Steven Spielberg (dir.), Leonardo DiCaprio, Tom Hanks 8.088985789287095
175 - Bacheha-Ye aseman (1997) - Starring: Majid Majidi (dir.), Mohammad Amir Naji, Amir Farrokh Hashemian 8.085719574829493
176 - The Gold Rush (1925) - Starring: Charles Chaplin (dir.), Charles Chaplin, Mack Swain 8.085063935835873
177 - Blade Runner (1982) - Starring: Ridley Scott (dir.), Harrison Ford, Rutger Hauer 8.084909507571735
178 - On the Waterfront (1954) - Starring: Elia Kazan (dir.), Marlon Brando, Karl Malden 8.081637699772394
179 - Before Sunrise (1995) - Starring: Richard Linklater (dir.), Ethan Hawke, Julie Delpy 8.080508541471659

In [24]:
#saving the list as dataframe
#then converting into .csv file
df = pd.DataFrame(list)
df.head()

,place,movie_title,rating,year,star_cast
0,1,The Shawshank Redemption,9.235228911762258,1994,"Frank Darabont (dir.), Tim Robbins, Morgan Fre..."
1,2,The Godfather,9.156085111265273,1972,"Francis Ford Coppola (dir.), Marlon Brando, Al..."
2,3,The Dark Knight,8.989211634325583,2008,"Christopher Nolan (dir.), Christian Bale, Heat..."
3,4,The Godfather Part II,8.984088961727375,1974,"Francis Ford Coppola (dir.), Al Pacino, Robert..."
4,5,12 Angry Men,8.95075650853193,1957,"Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb"

In [ ]:
df.to_csv('imdb_top_250_movies.csv',index = False)

In [25]:
"""
genres = [
    "Adventure",
    "Comedy",
    "Crime",
    "Drama",
    "Family",
    "Fantasy",
    "Horror",
    "Musical",
    "Mystery",
    "Romance",
    "Sci-Fi",
    "Sport",
    "Thriller"
]

url_dict = {}

for genre in genres:
    url = "https://www.imdb.com/search/title/?genres={}&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16"
    formated_url = url.format(genre)
    url_dict[genre] = formated_url
    
print(url_dict)
"""

{'Adventure': 'https://www.imdb.com/search/title/?genres=Adventure&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Comedy': 'https://www.imdb.com/search/title/?genres=Comedy&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Crime': 'https://www.imdb.com/search/title/?genres=Crime&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Drama': 'https://www.imdb.com/search/title/?genres=Drama&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Family': 'https://www.imdb.com/search/title/?genres=Family&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Fantasy': 'https://www.imdb.com/search/title/?genres=Fantasy&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Horror': 'https://www.imdb.com/search/title/?genres=Horror&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Musical': 'https://www.imdb.com/search/title/?genres=Musical&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Mystery': 'https://www.imdb.com/search/title/?genres=Mystery&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Romance': 'https://www.imdb.com/search/title/?genres=Romance&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Sci-Fi': 'https://www.imdb.com/search/title/?genres=Sci-Fi&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Sport': 'https://www.imdb.com/search/title/?genres=Sport&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'Thriller': 'https://www.imdb.com/search/title/?genres=Thriller&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16'}

In [27]:
HEADERS ={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

In [28]:
url = "https://www.imdb.com/search/title/?genres=Adventure&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16"

# Sending a request to the speciifed URL
resp = requests.get(url, headers=HEADERS)

# Converting the response to Beautiful Soup Object
content = BeautifulSoup(resp.content, 'lxml')

# Iterating throught the list of movies 
for movie in content.select('.lister-item-content'):
        
    try:
        # Creating a python dictonary
        data = {
            
            "title":movie.select('.lister-item-header')[0].get_text().strip(),
            "year":movie.select('.lister-item-year')[0].get_text().strip(),
            "certificate":movie.select('.certificate')[0].get_text().strip(),
            "time":movie.select('.runtime')[0].get_text().strip(),
            "genre":movie.select('.genre')[0].get_text().strip(),
            "rating":movie.select('.ratings-imdb-rating')[0].get_text().strip(),
            "metascore":movie.select('.ratings-metascore')[0].get_text().strip(),
            "simple_desc":movie.select('.text-muted')[2].get_text().strip(),
            "votes":movie.select('.sort-num_votes-visible')[0].get_text().strip()                
        }
    except IndexError:
        continue
        
    print(data)

{'title': '2.\nThe Lord of the Rings: The Return of the King\n(2003)', 'year': '(2003)', 'certificate': 'PG', 'time': '201 min', 'genre': 'Action, Adventure, Drama', 'rating': '9.0', 'metascore': '94        \n        Metascore', 'simple_desc': "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", 'votes': 'Votes:\n1,836,623\n| Gross:\n$377.85M'}
{'title': '4.\nInception\n(2010)', 'year': '(2010)', 'certificate': 'PG-13', 'time': '148 min', 'genre': 'Action, Adventure, Sci-Fi', 'rating': '8.8', 'metascore': '74        \n        Metascore', 'simple_desc': 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.', 'votes': 'Votes:\n2,336,649\n| Gross:\n$292.58M'}
{'title': '5.\nThe Lord of the Rings: The Two Towers\n(2002)', 'year': '(2002)', 'certificate': 'PG', 'time': '179 min', 'genre': 'Action, Adventure, Drama', 'rating': '8.8', 'metascore': '87        \n        Metascore', 'simple_desc': "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.", 'votes': 'Votes:\n1,658,409\n| Gross:\n$342.55M'}
{'title': '6.\nThe Lord of the Rings: The Fellowship of the Ring\n(2001)', 'year': '(2001)', 'certificate': 'PG', 'time': '178 min', 'genre': 'Action, Adventure, Drama', 'rating': '8.8', 'metascore': '92        \n        Metascore', 'simple_desc': 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 'votes': 'Votes:\n1,865,692\n| Gross:\n$315.54M'}
{'title': '8.\nThe Empire Strikes Back\n(1980)', 'year': '(1980)', 'certificate': 'PG', 'time': '124 min', 'genre': 'Action, Adventure, Fantasy', 'rating': '8.7', 'metascore': '82        \n        Metascore', 'simple_desc': 'After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.', 'votes': 'Votes:\n1,286,469\n| Gross:\n$290.48M'}
{'title': '9.\nInterstellar\n(2014)', 'year': '(2014)', 'certificate': 'G', 'time': '169 min', 'genre': 'Adventure, Drama, Sci-Fi', 'rating': '8.6', 'metascore': '74        \n        Metascore', 'simple_desc': "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", 'votes': 'Votes:\n1,810,507\n| Gross:\n$188.02M'}
{'title': '10.\nSen to Chihiro no kamikakushi\n(2001)', 'year': '(2001)', 'certificate': 'G', 'time': '125 min', 'genre': 'Animation, Adventure, Family', 'rating': '8.6', 'metascore': '96        \n        Metascore', 'simple_desc': "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.", 'votes': 'Votes:\n759,048\n| Gross:\n$10.06M'}
{'title': '11.\nStar Wars\n(1977)', 'year': '(1977)', 'certificate': 'G', 'time': '121 min', 'genre': 'Action, Adventure, Fantasy', 'rating': '8.6', 'metascore': '90        \n        Metascore', 'simple_desc': "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.", 'votes': 'Votes:\n1,359,038\n| Gross:\n$322.74M'}
{'title': '13.\nGladiator\n(2000)', 'year': '(2000)', 'certificate': 'R', 'time': '155 min', 'genre': 'Action, Adventure, Drama', 'rating': '8.5', 'metascore': '67        \n        Metascore', 'simple_desc': 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 'votes': 'Votes:\n1,492,869\n| Gross:\n$187.71M'}
{'title': '14.\nThe Lion King\n(1994)', 'year': '(1994)', 'certificate': 'G', 'time': '88 min', 'genre': 'Animation, Adventure, Drama', 'rating': '8.5', 'metascore': '88        \n        Metascore', 'simple_desc': 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 'votes': 'Votes:\n1,053,321\n| Gross:\n$422.78M'}
{'title': '16.\nSpider-Man: Into the Spider-Verse\n(2018)', 'year': '(2018)', 'certificate': 'PG', 'time': '117 min', 'genre': 'Animation, Action, Adventure', 'rating': '8.4', 'metascore': '87        \n        Metascore', 'simple_desc': 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.', 'votes': 'Votes:\n523,808\n| Gross:\n$190.24M'}
{'title': '17.\nAvengers: Endgame\n(2019)', 'year': '(2019)', 'certificate': '12A', 'time': '181 min', 'genre': 'Action, Adventure, Drama', 'rating': '8.4', 'metascore': '78        \n        Metascore', 'simple_desc': "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.", 'votes': 'Votes:\n1,119,296\n| Gross:\n$858.37M'}
{'title': '18.\nAvengers: Infinity War\n(2018)', 'year': '(2018)', 'certificate': '12A', 'time': '149 min', 'genre': 'Action, Adventure, Sci-Fi', 'rating': '8.4', 'metascore': '68        \n        Metascore', 'simple_desc': 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.', 'votes': 'Votes:\n1,071,615\n| Gross:\n$678.82M'}
{'title': '19.\nCoco\n(I) (2017)', 'year': '(I) (2017)', 'certificate': 'G', 'time': '105 min', 'genre': 'Animation, Adventure, Comedy', 'rating': '8.4', 'metascore': '81        \n        Metascore', 'simple_desc': "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.", 'votes': 'Votes:\n504,239\n| Gross:\n$209.73M'}
{'title': '21.\nMononoke-hime\n(1997)', 'year': '(1997)', 'certificate': 'PG', 'time': '134 min', 'genre': 'Animation, Action, Adventure', 'rating': '8.4', 'metascore': '76        \n        Metascore', 'simple_desc': "On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest he also meets San, the Mononoke Hime.", 'votes': 'Votes:\n393,999\n| Gross:\n$2.38M'}
{'title': '22.\nAliens\n(1986)', 'year': '(1986)', 'certificate': '15', 'time': '137 min', 'genre': 'Action, Adventure, Sci-Fi', 'rating': '8.4', 'metascore': '84        \n        Metascore', 'simple_desc': 'Fifty-seven years after surviving an apocalyptic attack aboard her space vessel by merciless space creatures, Officer Ripley awakens from hyper-sleep and tries to warn anyone who will listen about the predators.', 'votes': 'Votes:\n716,118\n| Gross:\n$85.16M'}
{'title': '23.\nRaiders of the Lost Ark\n(1981)', 'year': '(1981)', 'certificate': 'G', 'time': '115 min', 'genre': 'Action, Adventure', 'rating': '8.4', 'metascore': '85        \n        Metascore', 'simple_desc': 'Archaeology professor Indiana Jones ventures to seize a biblical artefact known as the Ark of the Covenant. While doing so, he puts up a fight against Renee and a troop of Nazis.', 'votes': 'Votes:\n962,698\n| Gross:\n$248.16M'}
{'title': '24.\nSpider-Man: No Way Home\n(2021)', 'year': '(2021)', 'certificate': 'PG-13', 'time': '148 min', 'genre': 'Action, Adventure, Fantasy', 'rating': '8.3', 'metascore': '71        \n        Metascore', 'simple_desc': "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.", 'votes': 'Votes:\n745,274\n| Gross:\n$804.75M'}
{'title': '25.\nUp\n(2009)', 'year': '(2009)', 'certificate': 'PG', 'time': '96 min', 'genre': 'Animation, Adventure, Comedy', 'rating': '8.3', 'metascore': '88        \n        Metascore', 'simple_desc': '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.', 'votes': 'Votes:\n1,040,146\n| Gross:\n$293.00M'}
{'title': '27.\nInglourious Basterds\n(2009)', 'year': '(2009)', 'certificate': 'R', 'time': '153 min', 'genre': 'Adventure, Drama, War', 'rating': '8.3', 'metascore': '69        \n        Metascore', 'simple_desc': "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.", 'votes': 'Votes:\n1,440,003\n| Gross:\n$120.54M'}
{'title': '28.\nToy Story\n(1995)', 'year': '(1995)', 'certificate': 'G', 'time': '81 min', 'genre': 'Animation, Adventure, Comedy', 'rating': '8.3', 'metascore': '95        \n        Metascore', 'simple_desc': "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.", 'votes': 'Votes:\n990,166\n| Gross:\n$191.80M'}
{'title': '29.\nStar Wars: Episode VI - Return of the Jedi\n(1983)', 'year': '(1983)', 'certificate': 'G', 'time': '131 min', 'genre': 'Action, Adventure, Fantasy', 'rating': '8.3', 'metascore': '58        \n        Metascore', 'simple_desc': "After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor's trap.", 'votes': 'Votes:\n1,050,087\n| Gross:\n$309.13M'}
{'title': '32.\nNorth by Northwest\n(1959)', 'year': '(1959)', 'certificate': 'G', 'time': '136 min', 'genre': 'Action, Adventure, Mystery', 'rating': '8.3', 'metascore': '98        \n        Metascore', 'simple_desc': 'A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies, and falls for a woman whose loyalties he begins to doubt.', 'votes': 'Votes:\n328,290\n| Gross:\n$13.28M'}
{'title': '33.\nInside Out\n(I) (2015)', 'year': '(I) (2015)', 'certificate': 'PG', 'time': '95 min', 'genre': 'Animation, Adventure, Comedy', 'rating': '8.2', 'metascore': '94        \n        Metascore', 'simple_desc': 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.', 'votes': 'Votes:\n710,920\n| Gross:\n$356.46M'}
{'title': '34.\nKimetsu no Yaiba: Mugen Ressha-Hen\n(2020)', 'year': '(2020)', 'certificate': 'R', 'time': '117 min', 'genre': 'Animation, Action, Adventure', 'rating': '8.2', 'metascore': '72        \n        Metascore', 'simple_desc': "After his family was brutally murdered and his sister turned into a demon, Tanjiro Kamado's journey as a demon slayer began. Tanjiro and his comrades embark on a new mission aboard the Mugen Train, on track to despair.", 'votes': 'Votes:\n57,973\n| Gross:\n$47.70M'}
{'title': '35.\nHauru no ugoku shiro\n(2004)', 'year': '(2004)', 'certificate': 'PG', 'time': '119 min', 'genre': 'Animation, Adventure, Family', 'rating': '8.2', 'metascore': '80        \n        Metascore', 'simple_desc': 'When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.', 'votes': 'Votes:\n394,464\n| Gross:\n$4.71M'}
{'title': '37.\nJurassic Park\n(1993)', 'year': '(1993)', 'certificate': 'PG', 'time': '127 min', 'genre': 'Action, Adventure, Sci-Fi', 'rating': '8.2', 'metascore': '68        \n        Metascore', 'simple_desc': "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.", 'votes': 'Votes:\n985,046\n| Gross:\n$402.45M'}
{'title': '38.\nIndiana Jones and the Last Crusade\n(1989)', 'year': '(1989)', 'certificate': 'G', 'time': '127 min', 'genre': 'Action, Adventure', 'rating': '8.2', 'metascore': '65        \n        Metascore', 'simple_desc': 'In 1938, after his father Professor Henry Jones, Sr. goes missing while pursuing the Holy Grail, Professor Henry "Indiana" Jones, Jr. finds himself up against Adolf Hitler\'s Nazis again to stop them from obtaining its powers.', 'votes': 'Votes:\n753,018\n| Gross:\n$197.17M'}
{'title': '42.\nThe Bridge on the River Kwai\n(1957)', 'year': '(1957)', 'certificate': 'PG', 'time': '161 min', 'genre': 'Adventure, Drama, War', 'rating': '8.2', 'metascore': '87        \n        Metascore', 'simple_desc': 'British POWs are forced to build a railway bridge across the river Kwai for their Japanese captors in occupied Burma, not knowing that the allied forces are planning a daring commando raid through the jungle to destroy it.', 'votes': 'Votes:\n221,376\n| Gross:\n$44.91M'}
{'title': '47.\nEverything Everywhere All at Once\n(2022)', 'year': '(2022)', 'certificate': 'R', 'time': '139 min', 'genre': 'Action, Adventure, Comedy', 'rating': '8.1', 'metascore': '81        \n        Metascore', 'simple_desc': 'An aging Chinese immigrant is swept up in an insane adventure, in which she alone can save the world by exploring other universes connecting with the lives she could have led.', 'votes': 'Votes:\n239,452'}
{'title': '48.\nKlaus\n(2019)', 'year': '(2019)', 'certificate': 'PG', 'time': '96 min', 'genre': 'Animation, Adventure, Comedy', 'rating': '8.1', 'metascore': '65        \n        Metascore', 'simple_desc': "A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg's new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.", 'votes': 'Votes:\n149,295'}

### Extract

In [1]:
import time

def get_movies(url, interval, file_name):
    HEADERS ={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}
    resp = requests.get(url, headers=HEADERS)
    content = BeautifulSoup(resp.content, 'lxml')

    movie_list = []

    for movie in content.select('.lister-item-content'):
        time.sleep(interval)
        try:
            data = {
                "title":movie.select('.lister-item-header')[0].get_text().strip(),
                "year":movie.select('.lister-item-year')[0].get_text().strip(),
                "certificate":movie.select('.certificate')[0].get_text().strip(),
                "time":movie.select('.runtime')[0].get_text().strip(),
                "genre":movie.select('.genre')[0].get_text().strip(),
                "rating":movie.select('.ratings-imdb-rating')[0].get_text().strip(),
                "metascore":movie.select('.ratings-metascore')[0].get_text().strip(),
                "simple_desc":movie.select('.text-muted')[2].get_text().strip(),
                "votes":movie.select('.sort-num_votes-visible')[0].get_text().strip()
                
            }
        except IndexError:
            continue
    
        movie_list.append(data)
         
        
    dataframe = pd.DataFrame(movie_list)
    dataframe.to_csv(file_name, index = False)

# Calling the function
#get_movies(url, 0, 'Adventure_movies.csv')

In [4]:
url = "https://www.imdb.com/search/title/?genres=Adventure&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16"
genres = [
    "adventure",
    "crime",
    "horror",
    "mystery",
    "sci-fi",
    "thriller"
]
url_dict = {}
for genre in genres:
    #url = "https://www.imdb.com/search/title/?genres={}&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16"
    formated_url = url.format(genre)
    url_dict[genre] = formated_url
    
print(url_dict)

{'adventure': 'https://www.imdb.com/search/title/?genres=Adventure&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'crime': 'https://www.imdb.com/search/title/?genres=Adventure&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'horror': 'https://www.imdb.com/search/title/?genres=Adventure&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'mystery': 'https://www.imdb.com/search/title/?genres=Adventure&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'sci-fi': 'https://www.imdb.com/search/title/?genres=Adventure&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16', 'thriller': 'https://www.imdb.com/search/title/?genres=Adventure&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=5aab685f-35eb-40f3-95f7-c53f09d542c3&pf_rd_r=N97GEQS6R7J9EV7V770D&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_16'}

In [7]:
for genre, url in url_dict.items():
    get_movies(url, 1, genre+'.csv')
    print("Saved:", genre+'.csv')

Saved: adventure.csv
Saved: crime.csv
Saved: horror.csv
Saved: mystery.csv
Saved: sci-fi.csv
Saved: thriller.csv

In [ ]:
##https://www.pycodemates.com/2022/02/scrape-movie-information-from-imdb-using-python-and-bs4.html
#ACCESS_KEY='AKIAVCI2VIMCOV4GR4FV'  
#SECRET_KEY='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'
#s3=boto3.client('s3',aws_access_key_id=ACCESS_KEY,aws_secret_access_key=SECRET_KEY)

### Transform

In [75]:
df_advent, df_crime, df_horror, df_mystery, df_sci, df_thriller = pd.read_csv('adventure.csv'), pd.read_csv('crime.csv'), pd.read_csv('horror.csv'), pd.read_csv('mystery.csv'), pd.read_csv('sci-fi.csv'), pd.read_csv('thriller.csv')

In [76]:
df_advent['genre'], df_crime['genre'], df_horror['genre'],df_mystery['genre'], df_sci['genre'], df_thriller['genre'] = 'adventure', 'crime', 'horror', 'mystery', 'scifi', 'thriller'
df_thriller

,title,year,certificate,time,genre,rating,metascore,simple_desc,votes
0,2.\nThe Lord of the Rings: The Return of the K...,(2003),PG,201 min,thriller,9.0,94 \n Metascore,Gandalf and Aragorn lead the World of Men agai...,"Votes:\n1,836,623\n| Gross:\n$377.85M"
1,4.\nInception\n(2010),(2010),PG-13,148 min,thriller,8.8,74 \n Metascore,A thief who steals corporate secrets through t...,"Votes:\n2,336,649\n| Gross:\n$292.58M"
2,5.\nThe Lord of the Rings: The Two Towers\n(2002),(2002),PG,179 min,thriller,8.8,87 \n Metascore,While Frodo and Sam edge closer to Mordor with...,"Votes:\n1,658,409\n| Gross:\n$342.55M"
3,6.\nThe Lord of the Rings: The Fellowship of t...,(2001),PG,178 min,thriller,8.8,92 \n Metascore,A meek Hobbit from the Shire and eight compani...,"Votes:\n1,865,692\n| Gross:\n$315.54M"
4,8.\nThe Empire Strikes Back\n(1980),(1980),PG,124 min,thriller,8.7,82 \n Metascore,After the Rebels are brutally overpowered by t...,"Votes:\n1,286,469\n| Gross:\n$290.48M"
5,9.\nInterstellar\n(2014),(2014),G,169 min,thriller,8.6,74 \n Metascore,A team of explorers travel through a wormhole ...,"Votes:\n1,810,507\n| Gross:\n$188.02M"
6,10.\nSen to Chihiro no kamikakushi\n(2001),(2001),G,125 min,thriller,8.6,96 \n Metascore,"During her family's move to the suburbs, a sul...","Votes:\n759,048\n| Gross:\n$10.06M"
7,11.\nStar Wars\n(1977),(1977),G,121 min,thriller,8.6,90 \n Metascore,Luke Skywalker joins forces with a Jedi Knight...,"Votes:\n1,359,038\n| Gross:\n$322.74M"
8,13.\nGladiator\n(2000),(2000),R,155 min,thriller,8.5,67 \n Metascore,A former Roman General sets out to exact venge...,"Votes:\n1,492,869\n| Gross:\n$187.71M"
9,14.\nThe Lion King\n(1994),(1994),G,88 min,thriller,8.5,88 \n Metascore,Lion prince Simba and his father are targeted ...,"Votes:\n1,053,321\n| Gross:\n$422.78M"
10,16.\nSpider-Man: Into the Spider-Verse\n(2018),(2018),PG,117 min,thriller,8.4,87 \n Metascore,Teen Miles Morales becomes the Spider-Man of h...,"Votes:\n523,808\n| Gross:\n$190.24M"
11,17.\nAvengers: Endgame\n(2019),(2019),12A,181 min,thriller,8.4,78 \n Metascore,After the devastating events of Avengers: Infi...,"Votes:\n1,119,296\n| Gross:\n$858.37M"
12,18.\nAvengers: Infinity War\n(2018),(2018),12A,149 min,thriller,8.4,68 \n Metascore,The Avengers and their allies must be willing ...,"Votes:\n1,071,615\n| Gross:\n$678.82M"
13,19.\nCoco\n(I) (2017),(I) (2017),G,105 min,thriller,8.4,81 \n Metascore,"Aspiring musician Miguel, confronted with his ...","Votes:\n504,239\n| Gross:\n$209.73M"
14,21.\nMononoke-hime\n(1997),(1997),PG,134 min,thriller,8.4,76 \n Metascore,On a journey to find the cure for a Tatarigami...,"Votes:\n393,999\n| Gross:\n$2.38M"
15,22.\nAliens\n(1986),(1986),15,137 min,thriller,8.4,84 \n Metascore,Fifty-seven years after surviving an apocalypt...,"Votes:\n716,118\n| Gross:\n$85.16M"
16,23.\nRaiders of the Lost Ark\n(1981),(1981),G,115 min,thriller,8.4,85 \n Metascore,Archaeology professor Indiana Jones ventures t...,"Votes:\n962,698\n| Gross:\n$248.16M"
17,24.\nSpider-Man: No Way Home\n(2021),(2021),PG-13,148 min,thriller,8.3,71 \n Metascore,"With Spider-Man's identity now revealed, Peter...","Votes:\n745,274\n| Gross:\n$804.75M"
18,25.\nUp\n(2009),(2009),PG,96 min,thriller,8.3,88 \n Metascore,78-year-old Carl Fredricksen travels to Paradi...,"Votes:\n1,040,146\n| Gross:\n$293.00M"
19,27.\nInglourious Basterds\n(2009),(2009),R,153 min,thriller,8.3,69 \n Metascore,"In Nazi-occupied France during World War II, a...","Votes:\n1,440,003\n| Gross:\n$120.54M"
20,28.\nToy Story\n(1995),(1995),G,81 min,thriller,8.3,95 \n Metascore,A cowboy doll is profoundly threatened and jea...,"Votes:\n990,166\n| Gross:\n$191.80M"
21,29.\nStar Wars: Episode VI - Return of the Jed...,(1983),G,131 min,thriller,8.3,58 \n Metascore,After a daring mission to rescue Han Solo from...,"Votes:\n1,050,087\n| Gross:\n$309.13M"
22,32.\nNorth by Northwest\n(1959),(1959),G,136 min,thriller,8.3,98 \n Metascore,A New York City advertising executive goes on ...,"Votes:\n328,290\n| Gross:\n$13.28M"
23,33.\nInside Out\n(I) (2015),(I) (2015),PG,95 min,thriller,8.2,94 \n Metascore,After young Riley is uprooted from her Midwest...,"Votes:\n710,920\n| Gross:\n$356.46M"
24,34.\nKimetsu no Yaiba: Mugen Ressha-Hen\n(2020),(2020),R,117 min,thriller,8.2,72 \n Metascore,After his family was brutally murdered and his...,"Votes:\n57,973\n| Gross:\n$47.70M"
25,35.\nHauru no ugoku shiro\n(2004),(2004),PG,119 min,thriller,8.2,80 \n Metascore,When an unconfident young woman is cursed with...,"Votes:\n394,464\n| Gross:\n$4.71M"
26,37.\nJurassic Park\n(1993),(1993),PG,127 min,thriller,8.2,68 \n Metascore,A pragmatic paleontologist touring an almost c...,"Votes:\n985,046\n| Gross:\n$402.45M"
27,38.\nIndiana Jones and the Last Crusade\n(1989),(1989),G,127 min,thriller,8.2,65 \n Metascore,"In 1938, after his father Professor Henry Jone...","Votes:\n753,018\n| Gross:\n$197.17M"
28,42.\nThe Bridge on the River Kwai\n(1957),(1957),PG,161 min,thriller,8.2,87 \n Metascore,British POWs are forced to build a railway bri...,"Votes:\n221,376\n| Gross:\n$44.91M"
29,47.\nEverything Everywhere All at Once\n(2022),(2022),R,139 min,thriller,8.1,81 \n Metascore,An aging Chinese immigrant is swept up in an i...,"Votes:\n239,452"
30,48.\nKlaus\n(2019),(2019),PG,96 min,thriller,8.1,65 \n Metascore,A simple act of kindness always sparks another...,"Votes:\n149,295"

In [77]:
df = pd.concat([df_advent, df_crime, df_horror, df_mystery, df_sci, df_thriller])
df

,title,year,certificate,time,genre,rating,metascore,simple_desc,votes
0,2.\nThe Lord of the Rings: The Return of the K...,(2003),PG,201 min,adventure,9.0,94 \n Metascore,Gandalf and Aragorn lead the World of Men agai...,"Votes:\n1,836,623\n| Gross:\n$377.85M"
1,4.\nInception\n(2010),(2010),PG-13,148 min,adventure,8.8,74 \n Metascore,A thief who steals corporate secrets through t...,"Votes:\n2,336,649\n| Gross:\n$292.58M"
2,5.\nThe Lord of the Rings: The Two Towers\n(2002),(2002),PG,179 min,adventure,8.8,87 \n Metascore,While Frodo and Sam edge closer to Mordor with...,"Votes:\n1,658,409\n| Gross:\n$342.55M"
3,6.\nThe Lord of the Rings: The Fellowship of t...,(2001),PG,178 min,adventure,8.8,92 \n Metascore,A meek Hobbit from the Shire and eight compani...,"Votes:\n1,865,692\n| Gross:\n$315.54M"
4,8.\nThe Empire Strikes Back\n(1980),(1980),PG,124 min,adventure,8.7,82 \n Metascore,After the Rebels are brutally overpowered by t...,"Votes:\n1,286,469\n| Gross:\n$290.48M"
...,...,...,...,...,...,...,...,...,...
26,37.\nJurassic Park\n(1993),(1993),PG,127 min,thriller,8.2,68 \n Metascore,A pragmatic paleontologist touring an almost c...,"Votes:\n985,046\n| Gross:\n$402.45M"
27,38.\nIndiana Jones and the Last Crusade\n(1989),(1989),G,127 min,thriller,8.2,65 \n Metascore,"In 1938, after his father Professor Henry Jone...","Votes:\n753,018\n| Gross:\n$197.17M"
28,42.\nThe Bridge on the River Kwai\n(1957),(1957),PG,161 min,thriller,8.2,87 \n Metascore,British POWs are forced to build a railway bri...,"Votes:\n221,376\n| Gross:\n$44.91M"
29,47.\nEverything Everywhere All at Once\n(2022),(2022),R,139 min,thriller,8.1,81 \n Metascore,An aging Chinese immigrant is swept up in an i...,"Votes:\n239,452"
30,48.\nKlaus\n(2019),(2019),PG,96 min,thriller,8.1,65 \n Metascore,A simple act of kindness always sparks another...,"Votes:\n149,295"

In [78]:
#import re
#df['title'].str.split("\n", 2, expand = True)
df['year'] = df['year'].str.replace('(', '', regex=True)
df['year'] = df['year'].str.replace(')', '', regex=True)
df['year'] = df['year'].str.replace('I 2015', '2015', regex=True)
df['year'] = df['year'].str.replace('I 2017', '2017', regex=True)
df['votes'] = df['votes'].str.replace(',', '', regex=True)
df['metascore'] = df['metascore'].str.replace(' \n', '', regex=True)
df['metascore'] = df['metascore'].str.replace(' Metascore', '', regex=True)
df['time'] = df['time'].str.replace(' min', '', regex=True)
df

,title,year,certificate,time,genre,rating,metascore,simple_desc,votes
0,2.\nThe Lord of the Rings: The Return of the K...,2003,PG,201,adventure,9.0,94,Gandalf and Aragorn lead the World of Men agai...,Votes:\n1836623\n| Gross:\n$377.85M
1,4.\nInception\n(2010),2010,PG-13,148,adventure,8.8,74,A thief who steals corporate secrets through t...,Votes:\n2336649\n| Gross:\n$292.58M
2,5.\nThe Lord of the Rings: The Two Towers\n(2002),2002,PG,179,adventure,8.8,87,While Frodo and Sam edge closer to Mordor with...,Votes:\n1658409\n| Gross:\n$342.55M
3,6.\nThe Lord of the Rings: The Fellowship of t...,2001,PG,178,adventure,8.8,92,A meek Hobbit from the Shire and eight compani...,Votes:\n1865692\n| Gross:\n$315.54M
4,8.\nThe Empire Strikes Back\n(1980),1980,PG,124,adventure,8.7,82,After the Rebels are brutally overpowered by t...,Votes:\n1286469\n| Gross:\n$290.48M
...,...,...,...,...,...,...,...,...,...
26,37.\nJurassic Park\n(1993),1993,PG,127,thriller,8.2,68,A pragmatic paleontologist touring an almost c...,Votes:\n985046\n| Gross:\n$402.45M
27,38.\nIndiana Jones and the Last Crusade\n(1989),1989,G,127,thriller,8.2,65,"In 1938, after his father Professor Henry Jone...",Votes:\n753018\n| Gross:\n$197.17M
28,42.\nThe Bridge on the River Kwai\n(1957),1957,PG,161,thriller,8.2,87,British POWs are forced to build a railway bri...,Votes:\n221376\n| Gross:\n$44.91M
29,47.\nEverything Everywhere All at Once\n(2022),2022,R,139,thriller,8.1,81,An aging Chinese immigrant is swept up in an i...,Votes:\n239452
30,48.\nKlaus\n(2019),2019,PG,96,thriller,8.1,65,A simple act of kindness always sparks another...,Votes:\n149295

In [79]:
df['num'], df['title'], df['ye'] = df['title'].str.split('\n', 2).str
df['vot'], df['votes'], df['grss'], df['gross'] = df['votes'].str.split('\n', 3).str
df

/tmp/ipykernel_91844/1737250600.py:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['num'], df['title'], df['ye'] = df['title'].str.split('\n', 2).str
/tmp/ipykernel_91844/1737250600.py:2: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['vot'], df['votes'], df['grss'], df['gross'] = df['votes'].str.split('\n', 3).str

,title,year,certificate,time,genre,rating,metascore,simple_desc,votes,num,ye,vot,grss,gross
0,The Lord of the Rings: The Return of the King,2003,PG,201,adventure,9.0,94,Gandalf and Aragorn lead the World of Men agai...,1836623,2.,(2003),Votes:,| Gross:,$377.85M
1,Inception,2010,PG-13,148,adventure,8.8,74,A thief who steals corporate secrets through t...,2336649,4.,(2010),Votes:,| Gross:,$292.58M
2,The Lord of the Rings: The Two Towers,2002,PG,179,adventure,8.8,87,While Frodo and Sam edge closer to Mordor with...,1658409,5.,(2002),Votes:,| Gross:,$342.55M
3,The Lord of the Rings: The Fellowship of the Ring,2001,PG,178,adventure,8.8,92,A meek Hobbit from the Shire and eight compani...,1865692,6.,(2001),Votes:,| Gross:,$315.54M
4,The Empire Strikes Back,1980,PG,124,adventure,8.7,82,After the Rebels are brutally overpowered by t...,1286469,8.,(1980),Votes:,| Gross:,$290.48M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,Jurassic Park,1993,PG,127,thriller,8.2,68,A pragmatic paleontologist touring an almost c...,985046,37.,(1993),Votes:,| Gross:,$402.45M
27,Indiana Jones and the Last Crusade,1989,G,127,thriller,8.2,65,"In 1938, after his father Professor Henry Jone...",753018,38.,(1989),Votes:,| Gross:,$197.17M
28,The Bridge on the River Kwai,1957,PG,161,thriller,8.2,87,British POWs are forced to build a railway bri...,221376,42.,(1957),Votes:,| Gross:,$44.91M
29,Everything Everywhere All at Once,2022,R,139,thriller,8.1,81,An aging Chinese immigrant is swept up in an i...,239452,47.,(2022),Votes:,NaN,NaN
30,Klaus,2019,PG,96,thriller,8.1,65,A simple act of kindness always sparks another...,149295,48.,(2019),Votes:,NaN,NaN

In [80]:
#df = df.drop(['num', 'ye', 'grss'], axis=1)
df = df[['title', 'year', 'certificate', 'time', 'genre', 'rating', 'metascore', 'simple_desc', 'votes', 'gross']]
df['gross'] = df['gross'].str.replace('$', '', regex=True)
df['gross'] = df['gross'].str.replace('M', '', regex=True)
df['gross'] = df['gross'].fillna(0)
df

/tmp/ipykernel_91844/3540422066.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gross'] = df['gross'].str.replace('$', '', regex=True)
/tmp/ipykernel_91844/3540422066.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gross'] = df['gross'].str.replace('M', '', regex=True)
/tmp/ipykernel_91844/3540422066.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gross'] = df['gross'].fillna(0)

,title,year,certificate,time,genre,rating,metascore,simple_desc,votes,gross
0,The Lord of the Rings: The Return of the King,2003,PG,201,adventure,9.0,94,Gandalf and Aragorn lead the World of Men agai...,1836623,377.85
1,Inception,2010,PG-13,148,adventure,8.8,74,A thief who steals corporate secrets through t...,2336649,292.58
2,The Lord of the Rings: The Two Towers,2002,PG,179,adventure,8.8,87,While Frodo and Sam edge closer to Mordor with...,1658409,342.55
3,The Lord of the Rings: The Fellowship of the Ring,2001,PG,178,adventure,8.8,92,A meek Hobbit from the Shire and eight compani...,1865692,315.54
4,The Empire Strikes Back,1980,PG,124,adventure,8.7,82,After the Rebels are brutally overpowered by t...,1286469,290.48
...,...,...,...,...,...,...,...,...,...,...
26,Jurassic Park,1993,PG,127,thriller,8.2,68,A pragmatic paleontologist touring an almost c...,985046,402.45
27,Indiana Jones and the Last Crusade,1989,G,127,thriller,8.2,65,"In 1938, after his father Professor Henry Jone...",753018,197.17
28,The Bridge on the River Kwai,1957,PG,161,thriller,8.2,87,British POWs are forced to build a railway bri...,221376,44.91
29,Everything Everywhere All at Once,2022,R,139,thriller,8.1,81,An aging Chinese immigrant is swept up in an i...,239452,0
30,Klaus,2019,PG,96,thriller,8.1,65,A simple act of kindness always sparks another...,149295,0

In [81]:
df.rename(columns = {'time':'time(min)', 'simple_desc':'description', 'gross':'gross_earning(M)'}, inplace = True)
df

/tmp/ipykernel_91844/3380135614.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {'time':'time(min)', 'simple_desc':'description', 'gross':'gross_earning(M)'}, inplace = True)

,title,year,certificate,time(min),genre,rating,metascore,description,votes,gross_earning(M)
0,The Lord of the Rings: The Return of the King,2003,PG,201,adventure,9.0,94,Gandalf and Aragorn lead the World of Men agai...,1836623,377.85
1,Inception,2010,PG-13,148,adventure,8.8,74,A thief who steals corporate secrets through t...,2336649,292.58
2,The Lord of the Rings: The Two Towers,2002,PG,179,adventure,8.8,87,While Frodo and Sam edge closer to Mordor with...,1658409,342.55
3,The Lord of the Rings: The Fellowship of the Ring,2001,PG,178,adventure,8.8,92,A meek Hobbit from the Shire and eight compani...,1865692,315.54
4,The Empire Strikes Back,1980,PG,124,adventure,8.7,82,After the Rebels are brutally overpowered by t...,1286469,290.48
...,...,...,...,...,...,...,...,...,...,...
26,Jurassic Park,1993,PG,127,thriller,8.2,68,A pragmatic paleontologist touring an almost c...,985046,402.45
27,Indiana Jones and the Last Crusade,1989,G,127,thriller,8.2,65,"In 1938, after his father Professor Henry Jone...",753018,197.17
28,The Bridge on the River Kwai,1957,PG,161,thriller,8.2,87,British POWs are forced to build a railway bri...,221376,44.91
29,Everything Everywhere All at Once,2022,R,139,thriller,8.1,81,An aging Chinese immigrant is swept up in an i...,239452,0
30,Klaus,2019,PG,96,thriller,8.1,65,A simple act of kindness always sparks another...,149295,0

In [70]:
#df['year'].unique()

In [84]:
df['title'] = df['title'].astype(str)
df['year'] = df['year'].astype(int)
df['certificate'] = df['certificate'].astype(str)
df['time(min)'] = df['time(min)'].astype(int)
df['genre'] = df['genre'].astype(str)
df['rating'] = df['rating'].astype(float)
df['metascore'] = df['metascore'].astype(int)
df['description'] = df['description'].astype(str)
df['votes'] = df['votes'].astype(int)
df['gross_earning(M)'] = df['gross_earning(M)'].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 186 entries, 0 to 30
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             186 non-null    object
 1   year              186 non-null    int64
 2   certificate       186 non-null    object
 3   time(min)         186 non-null    int64
 4   genre             186 non-null    object
 5   rating            186 non-null    float64
 6   metascore         186 non-null    int64
 7   description       186 non-null    object
 8   votes             186 non-null    int64
 9   gross_earning(M)  186 non-null    float64
dtypes: float64(2), int64(4), object(4)
memory usage: 16.0+ KB

/tmp/ipykernel_91844/1017861569.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].astype(str)
/tmp/ipykernel_91844/1017861569.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['year'].astype(int)
/tmp/ipykernel_91844/1017861569.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['certificate'] = df['certificate'].astype(str)
/tmp/ipykernel_91844/1017861569.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['time(min)'] = df['time(min)'].astype(int)
/tmp/ipykernel_91844/1017861569.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genre'] = df['genre'].astype(str)
/tmp/ipykernel_91844/1017861569.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].astype(float)
/tmp/ipykernel_91844/1017861569.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['metascore'] = df['metascore'].astype(int)
/tmp/ipykernel_91844/1017861569.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description'] = df['description'].astype(str)
/tmp/ipykernel_91844/1017861569.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['votes'] = df['votes'].astype(int)
/tmp/ipykernel_91844/1017861569.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gross_earning(M)'] = df['gross_earning(M)'].astype(float)

In [105]:
df.to_csv('clean-movie-review.csv', index=False)

## Load

## Load to s3, Redshift, DynamoDB

In [90]:
import boto3
AWS_KEY_ID='###'  
AWS_SECRET='###'
# instantiate an s3 object using boto3
s3 = boto3.client('s3', region_name = 'us-east-1',\
                  aws_access_key_id = AWS_KEY_ID, aws_secret_access_key = AWS_SECRET)

In [93]:
# create a bucket
bucket = s3.create_bucket(Bucket = 'movie-review-2022')

In [104]:
import os
path = 'rawfile/'
for root, dirs, files in os.walk(path):
    for name in files:
        if name.endswith(".csv"):
            s3.upload_file(Filename = name, Bucket = 'movie-review-2022', Key = 'raw/'+name)

In [107]:
s3.upload_file(Filename = 'clean-movie-review.csv', Bucket = 'movie-review-2022', Key = 'cleaned/clean-movie-review.csv')

In [ ]:
### Redshift configuration
### username = awsuser
### password = #########2020=Ab